### ISSUE TITLE
Unable to contact cas-user [at] apereo [dot] org

### ISSUE THREAD

**Issue by mostolog** [Jasig/mod_auth_cas#100]
README states: 
```
We welcome your feedback, suggestions and contributions. Contact us
via email if you have questions, feedback, code submissions,
and bug reports.  To reach the development team, send an e-mail to:

cas-user [at] apereo [dot] org
```

However, sending an email returns:
> We're writing to let you know that the group you tried to contact (cas-user) may not exist, or you may not have permission to post messages to the group

Providing Google's Group link instead would be great.

Regards

**Comment by dhawes** [comment]
Adding the Google Group link is a good suggestion, thanks.

**Comment by mostolog** [comment]
After sending a message to G'group I received:

```
The jasig.org email domain has been decommissioned and active lists and accounts have been migrated to the apereo.org domain. Subscriptions to the legacy lists have been transferred over to the new lists. Mail can no longer be posted to the old lists. Members of the active lists should have received a separate email.

For more information on available lists, see:
http://groups.apereo.org
```

...perhaps _another_ link would be better

**Comment by dhawes** [comment]
How about this one: https://groups.google.com/a/apereo.org/forum/#!forum/cas-user

**Comment by mostolog** [comment]
...just was I was looking for.
Thanks!
