### ISSUE TITLE
Questions about use of debug mode

### ISSUE THREAD

**Issue by dbz78** [Jasig/mod_auth_cas#106]
Hello,
With colleagues in my company, we are currently trying to fix issues with an application relying on mod_auth_cas for authentication. Problems are related to certificates.
In order to understand what happens, we used the directive

> CASDebug on

and added the directive 

> LogLevel debug

since the README states:

> Directive: 	CASDebug
> Default:	Off
> Description:	Enable or disable debugging mode for troubleshooting.  Please
>               note that **LogLevel must be set to Debug** for the VirtualHost in
>               order for these logs to be visible.

However, since we turned on LogLevel, **EVERY** module in Apache configuration traces to the standard **error.log** Apache log file, which becomes quickly huge and unmanageable.

Unfortunately, the application relies on Apache **2.2**, so the new syntax 

> LogLevel **auth_cas:debug**

available in Apache 2.4 is not working (we tried: Apache refuses to start! Oh, by the way, we are on a Windows platform).

So my questions:

1. If we have the capability to update to Apache 2.4.x (not likely in project context, but could happen), would the above syntax work? Any feedback on this?
2. Does anyone know a workaround in Apache 2.2.x to restrict debug trace to mod_auth_cas only?
3. Is there a directive to tell mod_auth_cas to trace in a **separate**, custom log file, instead of messying the standard Apache error.log?
(if not, it would be a **nice-to-have feature**, provided Apache module development rules allow for that)

Thanks for any reply,

**Comment by dhawes** [comment]
>    If we have the capability to update to Apache 2.4.x (not likely in project context, but could happen), would the above syntax work? Any feedback on this?

It will not work currently, but it is easily accomplished by adding the following line to mod_auth_cas.c (I stuck it right before cas_flock() as a quick and dirty test) and recompiling:

APLOG_USE_MODULE(auth_cas);

I need to review a little closer, but I intend on adding a patch for this.

This reference is mostly just so I don't forget:

https://httpd.apache.org/docs/2.4/developer/new_api_2_4.html#upgrading

>    Does anyone know a workaround in Apache 2.2.x to restrict debug trace to mod_auth_cas only?

I typically just grep out the lines that have "mod_auth_cas.c" in them. Is your file so unwieldy that something like that won't work?

>    Is there a directive to tell mod_auth_cas to trace in a separate, custom log file, instead of messying the standard Apache error.log? (if not, it would be a nice-to-have feature, provided Apache module development rules allow for that)

There is no current directive. I'd definitely need more convincing to go this route, as it's pretty standard to just write to Apache's error log.

If you're comfortable modifying source, it should be pretty trivial to output whatever log messages you need from mod_auth_cas to a file.

**Comment by dbz78** [comment]
dhawes, thanks for your reply.

Yes, when the log file receives debug information from more than 4 Apache modules, it becomes unwieldy in seconds. We can't "_grep_" the log files, since we are on a Windows platform. We can use "_findstr_" instead, which is equivalent, but we can't "_tail_" on findstr's output. So we manage to get some information from logs, but not in a very comfortable and handy way. findstr has to browse the full, ever growing log file each time we want to filter the very last lines - takes ages :-( when diagnosis should be real-time.

As of the hypothesis of modifying some code, it is not possible at this stage for the project. As I said in another post, the company contracted with an ISV. For contractual and liability reasons, we must NOT intervene on source code by ourselves, only ISV engineers can. For technical reasons, we can't do it anyway, as we are more Linux-oriented, and have nobody with knowledge on compiling Windows version of amended mod_auth_cas code. And the warning in [README.win32](https://github.com/Jasig/mod_auth_cas/blob/master/README.win32) is not heartening ...

> ### THIS README IS MAINTAINED FOR HISTORICAL REFERENCE ONLY AND
> ### HAS NOT BEEN KNOWN TO WORK SINCE v1.0.8
 

That's why I was asking about existing directives or workaround. The most efficient (and most advisable?) solution is to move to Apache 2.4.x, which offers all the options for distinct logging options. But it is also something to negociate with ISV, for the very same contractual and liability issues :-(

Thank you for your time and suggestions,

**Comment by dbz78** [comment]
Thanks dhawes for pushing the call to new Apache 2.4 log API in the code !

**Comment by dhawes** [comment]
#109 merged, adding per-module loglevel configuration.
