### ISSUE TITLE
README refers to defunct email address

### ISSUE THREAD

**Issue by eightnoneone** [Jasig/mod_auth_cas#111]
========================================================================
CONTACT INFORMATION AND WEBSITE
========================================================================
We welcome your feedback, suggestions and contributions. Contact us
via email if you have questions, feedback, code submissions,
and bug reports.  To reach the development team, send an e-mail to:

cas-user [at] apereo [dot] org

========================================================================

Emails to <cas-user@apereo.org> as noted at the bottom of the README are returned with:

"the group you tried to contact (cas-user) may not exist"

**Comment by dhawes** [comment]
https://github.com/Jasig/mod_auth_cas/issues/100

**Comment by eightnoneone** [comment]
Search fail. Carry on.
