### ISSUE TITLE
Service Url do not respect scheme

### ISSUE THREAD

**Issue by Falkurk** [Jasig/mod_auth_cas#113]
Hi,

I am trying to configure mod_auth_cas in front of Alfresco.

My Apache configuration is:

`CASCookiePath /tmp/
CASLoginURL https://cas-server-url:9043/cas/login
CASValidateURL https://cas-server-url:9043/cas/serviceValidate

<VirtualHost _default_:9043>

	<Location /share>
		AuthType CAS   
		require valid-user
		CASScope /share
	</Location>

	<Location /alfresco>
		AuthType CAS   
		require valid-user
		CASScope /alfresco
	</Location>

        SSLProxyEngine On

	#For tge example
	SSLProxyVerify none 
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off
	CASCertificatePath /usr/local/apache2/conf/ssl-socle/cert.crt

	SSLVerifyClient optional
	SSLOptions +StdEnvVars +ExportCertData	

	ProxyPass /alfresco https://localhost:8443/alfresco
	ProxyPassReverse /alfresco https://localhost:8443/alfresco

	ProxyPass /share https://localhost:8443/share
	ProxyPassReverse /share https://localhost:8443/share
</VirtualHost>`

When I trying to access to  https://localhost:9043/share I am redirected to:

https://cas-server-url:9043/cas/login?service=**http**%3a%2f%2flocalhost%3a9043%2fshare

Instead of

https://cas-server-url:9043/cas/login?service=**https**%3a%2f%2flocalhost%3a9043%2fshare

Is there a problem in my configuration or is it a bug ?

Sincerely

**Comment by dhawes** [comment]
I'll have to review the config a little closer to see if there's something else going on, but have you tried using CASRootProxiedAs:

CASRootProxiedAs https://localhost:9043

?

**Comment by Falkurk** [comment]
I tried to use CASRootProxiedAs https://localhost:9043

It work for the redirection to https://cas-server-url:9043/cas/login?service=https%3a%2f%2flocalhost%3a9043%2fshare

But mod_auth_cas still use http url after the cas ticket validation.

I try to use https://localhost/ (default port 443) and I have no problem (without using CASRootProxiedAs). I think there is a bug with https and specific port.

Sincerely

**Comment by dhawes** [comment]
Can you post your Apache version, mod_auth_cas version, and httpd.conf (minimal config that duplicates your issue) so I can test it? 

I haven't been able to duplicate what you're reporting so far.

**Comment by Falkurk** [comment]
Sure,

I work with:
- the docker Apache image 2.4.23
- libapache2-mod-auth-cas: 1.0.9.1-4 (install with apt-get)

[apache_conf.zip](https://github.com/Jasig/mod_auth_cas/files/507827/apache_conf.zip)

**Comment by dhawes** [comment]
You said https://localhost works as expected, which I would also expect from your config.

Is there some other config we're missing here? What is listening on 9093?

I would also recommend upgrading to v1.1.

**Comment by Falkurk** [comment]
Sorry I had the wrong apache config file in my last answer. 

To clarify the probleme all the url are:

- https://cas-server-url:9043  -> Jetty server with cas webapp and SSL connector on 9043
- https://localhost:9043 -> Apache server with mod_auth_cas 
- https://localhost:8443 -> Tomcat server with Alfresco webapp and SSL connector on 8443

Here the apache conf file with this configuration.

Concerning my problem, the redirection works well if I use https://localhost/ for the apache server instead of https://localhost:9043.

Sincerely
[apache_conf-v2.zip](https://github.com/Jasig/mod_auth_cas/files/510548/apache_conf-v2.zip)

**Comment by dhawes** [comment]
In your config, if you add "SSLEngine On" to your VirtualHost, do you get the proper behavior? It's possible that was causing the wrong service URL to be created in your original example.

The config files you posted are missing that directive in your VirtualHost and also have what looks like a problematic RewriteRule that will redirect non https traffic to port 443.

**Comment by Falkurk** [comment]
Indeed I think there is a problem with my RewriteRule. 

Thanks for the help.

**Comment by dhawes** [comment]
If you think it's just a config issue, feel free to close this issue. If you have evidence that there may still be an issue, please follow up.
