### ISSUE TITLE
Apache 2.4 - undefined symbol: ap_requires

### ISSUE THREAD

**Issue by guillaumemolter** [Jasig/mod_auth_cas#116]
Hi,

I have a working config with Apache 2.2 but was trying to move to 2.4 as all my other servers are using 2.4.

I'm getting the following error:
```
Starting httpd: httpd: Syntax error on line 353 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/conf.d/auth_cas.conf: Cannot load /etc/httpd/modules/mod_auth_cas.so into server: /etc/httpd/modules/mod_auth_cas.so: undefined symbol: ap_requires
```
This is on a freshly installed AWS Linux,  Apache 2.4.23, mod_auth_cas-1.1-3.el6.x86_64 using RHEL6.

My understanding was that Apache 2.4 was added in #86 (1.1 release according to #49).
However `ap_requires` was [removed in 2.4 ](http://httpd.apache.org/docs/current/developer/new_api_2_4.html#http_core).

Am I missing something??

Thanks for your help

**Comment by dhawes** [comment]
It would seem that your mod_auth_cas package is compiled against Apache 2.2. You'll need a version compiled against 2.4.

I would recommend compiling mod_auth_cas yourself and then retrying. Otherwise, you'll need to take it up with the package maintainer.

**Comment by guillaumemolter** [comment]
@dhawes thank you, I have contacted the package maintainer to see if he can do something about it. If not I'll self compile. Closing this for now. Will re-open if the solution suggested doesn't solve the issue.
