### ISSUE TITLE
Issue with CASAuthNHeader, user info headers

### ISSUE THREAD

**Issue by quitos90** [Jasig/mod_auth_cas#122]
I am currently working on securing a PHP application with Apache mod_auth_cas. I managed to authenticate users, get the cookie and generate the cookie file with user information. However, I am facing the following issue:

The module is not writing the HTTP Headers with the user info. I do not know why the user info is not displayed when the login is successful. The validation in place is SAML.

This is my mod_auth_config:
```

<IfModule !ssl_module>
    LoadModule ssl_module modules/mod_ssl.so
</IfModule>
LoadModule auth_cas_module modules/mod_auth_cas.so

CASVersion 2
CASDebug On

CASLoginURL http://********/index.html
CASValidateURL https://**********/cas/samlValidate
CASValidateSAML On


<VirtualHost *:8010>
	DocumentRoot *********
	ErrorLog logs/cas_error_log
	CustomLog logs/cas_access_log combined
	LogLevel debug
	
	<Location /secured.php>
		Authtype CAS
		require valid-user
		
		CASScope /
		
		CASAuthNHeader CAS_firstname
		CASAuthNHeader CAS_userType
		
	</Location>

</VirtualHost>

```

This is my secure page with the headers:

**Response Headers:**
Age:0
Connection:Keep-Alive
Content-Length:842
Content-Type:text/html; charset=UTF-8
Date:Fri, 20 Jan 2017 10:02:22 GMT
Proxy-Connection:Keep-Alive
Server:Apache/2.2.15 (Oracle)
X-Powered-By:PHP/5.3.3
**Request Headers:**
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Cookie:_ga=GA1.1.2137298612.1484900359; **# MOD_AUTH_CAS**=1efb0b1dd5ad5a3a8d1337ddf0948115; BCSI-CS-92a12fdef0366f25=2
Host:***********:8010
Proxy-Connection:keep-alive
Referer:http://********:8010/index.php?service=http%3a%2f%2f**********%3a8010%2fsecured.php
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

SAML Cache Cookie:

```
<attribute name="firstname">
        <value>Marcos</value>
  </attribute>

```
```
 <attribute name="userType">
        <value>PS</value>
  </attribute>

```

PD: I tried changing prefix, and put one without underscore and nothing.

**Comment by dhawes** [comment]
CASAuthNHeader sets HTTP headers used by the *server*, not the response headers to the *client*.

This thread may be useful:

https://groups.google.com/a/apereo.org/forum/#!msg/cas-user/fDjZ9gitP3M/6ZJ1q7CFCAAJ

**Comment by quitos90** [comment]
It's works!!

My problem was that I checked request headers in a public page.

Thank you so much for the answer! :) :)
