### ISSUE TITLE
Not compatible with Apache httpd 2.4.x

### ISSUE THREAD

**Issue by maxamillion** [Jasig/mod_auth_cas#49]
MOD_AUTH_CAS: CASCookiePath '/dev/null' is not a directory or does not end in a trailing '/'!\n", 149) = 149

**Comment by jamgregory** [comment]
Are there any plans to merge the @klausdieterkrannich's changes into this repo? We're in the process of upgrading our servers to use Apache 2.4, and ideally need to use this module.

**Comment by pames** [comment]
I don't have any active CAS deployments to test against (and haven't in years), so I'm not keen to merge something I can't really test/support.  That said, maybe there are others with active deployments that are willing to take this on who also have commit rights on the project (e.g. the VA Tech folks).

**Comment by dhawes** [comment]
I have tested the 2.4 merge request and also recommend it to users here at VT. I would merge it based on that, but since I'm newer to the project than most I haven't done so.

I've actually been meaning to bring this up on the dev list as there are a few merge requests that I think can be merged and maybe tagged as a new release.

**Comment by forsetti** [comment]
@dhawes  Can you note the pull requests that yuo've vetted (set milestone
to "1.10" might be easiest way) ?

On Wed, Oct 21, 2015 at 3:21 PM, David Hawes <notifications@github.com>
wrote:

> I have tested the 2.4 merge request and also recommend it to users here at
> VT. I would merge it based on that, but since I'm newer to the project than
> most I haven't done so.
>
> I've actually been meaning to bring this up on the dev list as there are a
> few merge requests that I think can be merged and maybe tagged as a new
> release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jasig/mod_auth_cas/issues/49#issuecomment-149999700>.
>



-- 
matt@forsetti.com
PGP: E2144AD8

**Comment by dhawes** [comment]
Milestones set:

https://github.com/Jasig/mod_auth_cas/milestones/1.0.10

**Comment by jhg03a** [comment]
@dhawes I tried testing your code today without success when using the jasigcas.herokuapp.com test server.  I used the compile instructions on RHEL 6 following these steps: http://plone.uconn.edu/workspaces/uits-linux/standard-operating-procedures-sop/os-installs/red-hat/rhel6-installing-mod_auth_cas

Looking at the response stream, it appears that it's getting chopped off part-way through.  http://pastebin.ca/3233738

**Comment by dhawes** [comment]
@jhg03a Are you using /serviceValidate or /samlValidate? It looks like only the former is configured on that server. When I try /samlValidate I get redirected to /login, which is exactly what your response shows.

/serviceValidate does seem to work.

**Comment by jhg03a** [comment]
@dhawes I'm seeing the same thing regardless.  In case it's relevant, here is my apache .conf I'm testing with.  http://pastebin.ca/3235278

**Comment by dhawes** [comment]
@jhg03a Try the following:

    CASLoginURL https://jasigcas.herokuapp.com/login
    CASValidateURL https://jasigcas.herokuapp.com/serviceValidate

**Comment by jhg03a** [comment]
Ah ha! That did it.  Now things are working fine with the pull request.  Thanks @dhawes!

**Comment by jhg03a** [comment]
I wish they would document on that page what all the appropriate URL are.  Based on their documentation their url should have a /cas/ in the middle of it.

**Comment by rsajan** [comment]
Is mod_auth_cas considered fully compatible with Apache 2.4? 

I noticed this merge: 
https://github.com/Jasig/mod_auth_cas/pull/86

I've installed mod_auth_cas and am using it successfully with Apache 2.4

The main README still indicates support is for Apache 2.0 and 2.2

Also fyi on RHEL I need to install these: gcc openssl-devel libcurl-devel automake libtool httpd-devel

Thank you for all your work on this.

**Comment by dhawes** [comment]
Apache 2.4 support is in git master, and should be released soon as v1.1. 

I hesitate to say "fully compatible", but we will take care of issues as they arise. :)

Thanks for the note about the README. That is one of the things we need to update before the release.

**Comment by dhawes** [comment]
Apache 2.4 support has been added in v1.1.

**Comment by Smy** [comment]
Thank you @dhawes and the mod_auth_cas team for this release !

**Comment by gcarroll** [comment]
As soon as I can g

**Comment by gcarroll** [comment]
hello

**Comment by gcarroll** [comment]
Hello,

Sorry about that.  Seems my iPhone decided to decide that was ready to post when I wasn't.  I have downloaded this release and first need to get my CAS server configured and working beforehand.  I will report any issues here if I run into any.

+1 for everyone's work on this module.

Geordie Carroll 
Interior Technology Inc
