### ISSUE TITLE
Production-Ready Release with "Require cas-attribute" Support

### ISSUE THREAD

**Issue by laughingbovine** [Jasig/mod_auth_cas#57]
I'm using 1.0.9.1 and notice that there is no support for a "Require cas-attribute" directive, but it's there in the master and attz branches.  Can these branches be considered ok for production?  I guess I'm hoping someone forgot to tag 1.0.10.

**Comment by ruckc** [comment]
I've been using my fork of Jasig's repo in production for a while now with
the 'Require cas-attribute' with no issues against both cas 3.3.5 and cas
3.5.2

**Comment by dhawes** [comment]
v1.1 has been released.
