### ISSUE TITLE
README.md references 1.0.10 but no such release

### ISSUE THREAD

**Issue by LucaFilipozzi** [Jasig/mod_auth_cas#71]
The README.md file references 1.0.10 but the last release tag (three years ago) was for 1.0.9.1.

Please either remove the reference from the README.md (in which case, why are you not 'releasing'?) or create a 1.0.10 release (in which case, will you resume regular releases?).

Thanks.

**Comment by arusso** [comment]
With all the new SAML support, it would be nice to see 1.0.10 tagged so package maintainers can package up the new functionality. Is this something someone like me (who pretty much does this already internally) could help with?

**Comment by dbz78** [comment]
Hello,
**+1** for the need of an "official" 10.0.10 release.
We have operational needs of some functionalities that the new version addresses, and an "official" release would ease contractual relationships with IT providers and integrators.
Last 10.9.0.1 release is way too old and does **not** fix issues we have.

Latest commit is reported on 23 Aug **2014**, so the current working version is stable, isn't it?
Any plans for releasing soon?
I have no knowledge of complexity or amount of work needed.
What is needed?
How to help (though I am illiterate in github matters)?

Thanks in advance

**Comment by LucaFilipozzi** [comment]
Indeed, +1.  It would be very helpful to package maintainers for releases to be properly tagged.

I'm also happy to assist, ongoing.  

In that vein, I've offered to contribute (but not received a positive response) RPM packaging scripts.  See https://github.com/LucaFilipozzi/mod_auth_cas.  Happy to generate a pull request if there's interest.  Perhaps a YUM repo could be established?

As a Debian Developer, I could also help with Debian package.  I'll ping the package maintainer, there.

**Comment by serac** [comment]
I think we ought to accept your offer for RPM and Debian packages. I will speak to a colleague about a suitable YUM repository and follow up.

**Comment by gcarroll** [comment]
I am looking to utilize CAS and the php CAS modules,  I am still a CAS greenhorn!  I am willing to be a contributor on this project, as many seem to have an interest including myself!  If there is a todo or anything of that sort please let me know.

Geordie .Carroll
Interior Family
Interior Technology Inc

**Comment by dhawes** [comment]
A 1.1 release is imminent and will be based on https://github.com/dhawes/mod_auth_cas/tree/v1.1. It will contain support for Apache 2.4 as well as some patches for other common issues that come up often.

**Comment by gcarroll** [comment]
+1 Thanks, Andrew.  Right now too I am still focusing on getting my uPortal/CAS working. I am a bit lost in this process.  

I will be using the php CAS for connectivity to phpBB and Drupal ONCE I overcome a hurdle with php apps not installing.  Not sure what the issue is.

**Comment by serac** [comment]
I asked a couple of my folks about Linux packages, and they both recommended we shoot for an official or semi-official repository. I should note that packages _do_ already exist, they're just for old versions:

http://rpmfind.net/linux/rpm2html/search.php?query=mod_auth_cas
https://packages.debian.org/jessie/libapache2-mod-auth-cas

We're hopeful that the existing maintainers are tracking the source repo and new versions based on 1.1 will magically appear when it's tagged. We'll continue to be vigilant, and we can ping the existing maintainers if needed to overcome inertia.

**Comment by LucaFilipozzi** [comment]
Certainly, the first step to making it possible for package maintainers to package mod_auth_cas is for this project to tag its releases.  Debian, for example, has an automated system for alerting the package maintainer new release is detected.  This project's track record at tagging its releases could stand for some improvement (cf this 1.5yo ticket).

The second step is to ask the package maintainers whether they will back port newer versions of the mod_auth_cas to stable releases of their distributions.  In the case of Debian, this means that the package maintainer would upload to jessie-backports (aka stable-backports) in addition to sid (aka unstable).  If the package maintainer has no such intention, then users of mod_auth_cas are stuck following the advice often given in the mailing list: just build from source.

I found this advice unappealing for two reasons: (1) Without a tagged release, it's more difficult to know what's been compiled.  Sure, I could check out based on git commit, but I'd much prefer a tag, which is why I forked the repo.  (2) Also, I don't want to just run axps and copy the resulting dynamically loaded module to the right directory.  I'd like a proper RPM or DEB that I can install or uninstall, which is why I added packaging details to my repo.  In order to assist others who need to build from source because the latest versions aren't being backported, you could pull in the RPM and DEB packaging instructions / templates.

So, while you may not want to take me up on my offer to work with the current maintainers, I ask that you consider doing three things:

(1) Please tag your releases.

(2) Please consider adding packaging instructions / templates.

(3) [You've already said no, but for completeness.] Please consider hosting compiled RPMs / DEBs for various linux variants so that users can access newer releases of mod_auth_cas for stable releases of RedHat/CentOS/etc. and Debian/Ubuntu where the respective package maintainers do not intend to backport.

**Comment by forsetti** [comment]
FYI - see PR #87 .  1.1 to be tagged soon.

**Comment by dhawes** [comment]
v1.1 has been tagged.

It looks like it's making its way into packages:

https://bugzilla.redhat.com/show_bug.cgi?id=1177042
