### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by dougman82** [Jasig/mod_auth_cas#84]
I am using mod_auth_cas release 1.0.9.1, and am trying to work with the CAS REST API (as outlined here: https://wiki.jasig.org/display/casum/restful+api), but am having difficulties.

In my Apache configuration, I am allowing all access to the "/cas" endpoint, and then using "AuthType CAS" and "Require valid-user" for the "/doug" endpoint (my test application). For normal operation, everything is working great. But now I have enabled the CAS REST service to allow a headless application to access the CAS-protected resources.

To test this, I have followed the behavior outlined in the above link and written a Java client that requests a TGT resource from /cas/v1/tickets and then with that in hand, requests a service ticket. That part works wonderfully. Once it has a service ticket in hand, it tries to access the "/doug" endpoint, appending "?ticket=<the service ticket>" to the end of the URL, but the result is that it is presented with the CAS login page instead of the desired resource.

I took a look at the Apache logs (I can post them if that would help), and it looks as if mod_auth_cas is, in fact reading the service ticket and even validating it against CAS (I see the "serviceResponse" XML with an "authenticationSuccess" element and my username).

But right after that, it shows that a cookie is placed as a header (MOD_AUTH_CAS_S), and then the connection is closed. Then I see a new connection, in which the "Require valid-user" directive fails, and then mod_auth_cas redirects to the CAS login URL, and that's where it ends.

I feel like my client is working properly because it works when trying to access a web application that is configured to directly use CAS (with the Java cas-client-core libraries) instead of using mod_auth_cas. But I definitely may be overlooking something (such as that cookie header?).

**Comment by pames** [comment]
Your client will need to take the MOD_AUTH_CAS_S cookie and add it to the cookie jar for your HTTP client for subsequent requests to the /doug endpoint.

**Comment by dougman82** [comment]
Ok, that works great (and makes sense). Thanks for the super-quick response!
