### ISSUE TITLE
AuthType Cas working from .htaccess but not from httpd config

### ISSUE THREAD

**Issue by racooper** [Jasig/mod_auth_cas#95]
I have what I would consider a strange issue.  First the specs:
CentOS 7
Apache 2.4
mod_auth_cas 1.0.9.1 from https://github.com/djjudas21/mod_auth_cas to build RPM with SSL-CA-chains.patch from https://github.com/klausdieterkrannich/mod_auth_cas

Using the above configuration, I can authenticate to a directory with .htaccess setting "AuthType Cas" using AllowOverride All in the <directory ...> configuration section for that path.  However, trying to put the AuthType Cas directive into the Apache config itself fails, it doesn't even attempt to redirect to our CAS service.

auth_cas.conf
````
LoadModule auth_cas_module modules/mod_auth_cas.so

CASDebug on

# Cookie path must be given as an absolute path with a trailing slash
CASCookiePath /var/run/mod_auth_cas/

# Certificate path may be a file or a directory of certificates symlinked by
# their hashed names
CASCertificatePath /etc/pki/tls/certs/ca-bundle.crt

# The URL to the CAS server - Production
CASLoginURL https://cas.domain.com/cas/login
CASValidateURL https://cas.domain.com/cas/serviceValidate
CASProxyValidateURL https://cas.domain.com/cas/proxyValidate

#CASValidateServer Off
````
test.conf
````
<Directory /var/www/html/testdir>
  AllowOverride All
  Require all granted
</directory>
````
If I put "AuthType Cas" in the test.conf file it gets ignored, though it works in .htaccess, with all other settings the same.
````
<Directory /var/www/html/testdir>
  AllowOverride All
  Require all granted
  AuthType Cas
</directory>
````

**Comment by dhawes** [comment]
I would think you'd want to replace "Require all granted" with "Require valid-user" or similar to attempt CAS authentication. "Require all granted" allows access unconditionally, so there's no reason to use CAS.

Does your .htaccess file have a require directive?

Note that I am using Jasig:master which includes better support for 2.4 authorization like RequireAny and RequireAll. I would recommend upgrading and testing. Perhaps being more explicit with these directives will make the behavior a bit clearer?

**Comment by racooper** [comment]
I should have included that: a working .htaccess file only contains
````
AuthType Cas
require valid-user
````
