### ISSUE TITLE
CASRootProxiedAs and URL parameters

### ISSUE THREAD

**Issue by danizen** [Jasig/mod_auth_cas#96]
I have an application protected by CAS behind an f5 BigIP load balancer (their LTM module).   The Apache 2.2 host is running in `NameVirtualHos` mode on port 4000.   With `CASRootProxiedAs`, basic authentication is working, however, CAS is messing up the URL rewrite after `serviceValidate`.   This prevents any deep bookmarks from resolving.

So, if I start with an URL such as `https://examplehost-qa.nlm.nih.gov/admin/patron/list?username=b&barcode=&filter=Apply&orderby=-username`, then the response comes back as expected with the additional ticket parameter.  serviceValidate works, but the final URL is `https://examplehost-qa.nlm.nih.gov/admin/patron/list?username%3db%26barcode%3d%26filter%3dApply%26orderby%3d-username`

I stumbled upon this because another copy of the application is running on the same host, but on port 80 rather than port 4000.  In this case, `CASRootProxiedAs` is not present, and the parameters come across fine.

Also - running CentOS 6.x with mod_auth_cas 1.0.9.1-1 from EPEL rpm.   I may try to run a more recent release before creating a pull request/looking at code.

**Comment by danizen** [comment]
I don't know when it was fixed, but I can see the error in the download of 1.0.9.1 and it is not in the latest code.   I'd still like a JIRA ticket or github issue reference so I can tell my systems guys why if needed.

-Thanks!

**Comment by dhawes** [comment]
Could it be related to #56?

And just so I'm clear, git master is working correctly for you?

**Comment by danizen** [comment]
> And just so I'm clear, git master is working correctly for you?

Yes, master is working for me.   Blame says it was fixed in f1d911905b45b5d068ea4a34f906f89eb21ea04f, so thanks to Matt.

**Comment by danizen** [comment]
I also just noticed that mod_auth_cas isn't in EPEL 7 or CentOS 7.   Do you know who maintains the package in EPEL?

**Comment by forsetti** [comment]
Hi Dan,

When we release mod_auth_cas 1.1 (real soon now), I will ping the Red Hat
packager to update the packages (I work for Red Hat, but I am not an
engineer or package maintainer myself).

-Matt

On Tue, Apr 5, 2016 at 10:33 AM, Dan Davis <notifications@github.com> wrote:

> I also just noticed that mod_auth_cas isn't in EPEL 7 or CentOS 7. Do you
> know who maintains the package in EPEL?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jasig/mod_auth_cas/issues/96#issuecomment-205835124>
>



-- 
matt@forsetti.com
PGP: E2144AD8

**Comment by danizen** [comment]
I checked on #fedora-devel and 1.1 is that for which they wait.

**Comment by andrew-timmes** [comment]
Probably not the best place to ask, but is there a timeframe on the mod_auth_cas 1.1 release? I have a set of apache 2.4 servers I'm attempting to configure on CentOS 7-derivative servers and could really use the upstream EPEL/Fedora SRPMS. :)

**Comment by forsetti** [comment]
Hi Andrew - I'm working on the release notes, and one final build bug (that
has a simple workaround, so may release anyway).  I am in a tough travel
cycle, but i'm expecting within April.

**Comment by dhawes** [comment]
v1.1 has been released.
